import { Inter } from 'next/font/google'
import './globals.css'
import clsx from 'clsx'
import Sidebar from '@/component/sidebar'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const inter = Inter({ subsets: ['latin'], variable: '--font-inter', })

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html 
    lang="en"
    className={clsx('font-sans text-black bg-white dark:bg-black dark:text-white', inter.variable)}>
      <body className="antialiased max-w-4xl mb-40 flex flex-col md:flex-row mx-4 mt-8 md:mt-20 lg:mt-32 lg:mx-auto">
        <Sidebar/>
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
